#!/bin/bash

# finish elastic install (this needs to be done here because _SANDBOX_ID is not available outside of the setup script)
export _SANDBOX_ID=$_SANDBOX_ID
/usr/local/bin/elastic-start.sh

# setup openai (this needs to be done here because secrets are not available outside of the setup script)
export SA_LLM_PROXY_BEARER_TOKEN=$SA_LLM_PROXY_BEARER_TOKEN
/usr/local/bin/elastic-openai.sh

/usr/local/bin/apmotel-install.sh
