services:

  resources:
    build:
      context: ./resources
    restart: on-failure
    ports:
      - "9010:9010"
    environment:
      BACKLOAD_DATA: true
      SOLVE_ALL: true
      ERRORS: false

      KIBANA_URL: ${KIBANA_URL}
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
      ELASTICSEARCH_USER: ${ELASTICSEARCH_USER}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      OTEL_EXPORTER_OTLP_ENDPOINT_PLAYBACK_APM: "http://collector_playback:4318"
      OTEL_EXPORTER_OTLP_ENDPOINT_PLAYBACK_ELASTICSEARCH: "http://collector_playback:4319"
    depends_on:
      collector_playback:
        condition: service_healthy

  collector_playback:
    image: docker.elastic.co/beats/elastic-agent:8.16.1
    restart: on-failure
    healthcheck:
      test: curl --fail http://localhost:13133/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1m
    ports:
      - "4318:4318"
      - "4319:4319"
    volumes:
      - ./src/collector/collector_playback.yml:/collector.yml
    entrypoint: "/usr/share/elastic-agent/elastic-agent"
    command: ["otel", "-c", "/collector.yml"]
    environment:
      ELASTIC_APM_SERVER_ENDPOINT: ${ELASTIC_APM_SERVER_ENDPOINT}
      ELASTIC_APM_SERVER_SECRET: ${ELASTIC_APM_SERVER_SECRET}
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
      ELASTICSEARCH_APIKEY: ${ELASTICSEARCH_APIKEY}