services:

  resources:
    build:
      context: ./resources
    restart: on-failure
    ports:
      - "9010:9010"
    environment:
      BACKLOAD_DATA: ${BACKLOAD_DATA:-true}
      SOLVE_ALL: ${SOLVE_ALL:-true}
      KIBANA_URL: ${KIBANA_URL}
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
      ELASTICSEARCH_USER: ${ELASTICSEARCH_USER}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      OTEL_EXPORTER_OTLP_ENDPOINT_PLAYBACK_APM: "http://collector_playback:4318"
      OTEL_EXPORTER_OTLP_ENDPOINT_PLAYBACK_ELASTICSEARCH: "http://collector_playback:4319"

  trader:
    build:
      context: ./src/trader/
    restart: on-failure
    healthcheck:
      test: curl --fail http://127.0.0.1:9001/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1m
    ports:
      - "9001:9001"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4317"
    depends_on:
      router:
        condition: service_healthy
      collector:
        condition: service_healthy

  monkey:
    build:
      context: ./src/monkey/
    restart: on-failure
    healthcheck:
      test: curl --fail http://127.0.0.1:9002/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1m
    ports:
      - "9002:9002"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4317"
    depends_on:
      trader:
        condition: service_healthy
      collector:
        condition: service_healthy

  router:
    build:
      context: ./src/router/
    restart: on-failure
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:9000/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1m
    ports:
      - "9000:9000"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"

      RECORDER_HOST_1: "recorder-java"
      RECORDER_HOST_2: "recorder-go"
      RECORDER_HOST_CANARY: "recorder-go-zero"
    depends_on:
      recorder-go:
        condition: service_healthy
      recorder-java:
        condition: service_healthy
      collector:
        condition: service_healthy

  recorder-go:
    build:
      context: ./src/recorder-go/
    restart: on-failure
    volumes:
      - ./logs:/logs
    command: ["-logfile=/logs/recorder-go.json"]
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:9003/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1m
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4317"
  
      POSTGRES_HOST: "postgresql"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "admin"
    depends_on:
      postgresql:
        condition: service_healthy
      collector:
        condition: service_healthy
      notifier:
        condition: service_healthy

  recorder-go-zero:
    build:
      context: ./src/recorder-go-zero/
    restart: on-failure
    volumes:
      - ./logs:/logs
      - /proc:/host/proc
    command: ["-logfile=/logs/recorder-go-zero.json"]
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:9003/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1m
    environment:
      POSTGRES_HOST: "postgresql"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "admin"
    depends_on:
      postgresql:
        condition: service_healthy
      collector:
        condition: service_healthy
      notifier:
        condition: service_healthy
    pid: "host"

  recorder-go-zero-ebpf:
    image: otel/autoinstrumentation-go
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4318"
      OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
      OTEL_SERVICE_NAME: "recorder-go-zero"
      OTEL_GO_AUTO_TARGET_EXE: "/recorder-zero"
      OTEL_PROPAGATORS: "tracecontext,baggage"
      OTEL_LOG_LEVEL: "debug"
      OTEL_GO_AUTO_INCLUDE_DB_STATEMENT: "true"
    volumes:
      - /proc:/host/proc
    depends_on:
      - recorder-go-zero
    privileged: true
    pid: "host"

  recorder-java:
    build:
      context: ./src/recorder-java/
    restart: on-failure
    healthcheck:
      test: curl --fail http://127.0.0.1:9003/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1m
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"

      POSTGRES_HOST: "postgresql"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "admin"
    depends_on:
      postgresql:
        condition: service_healthy
      collector:
        condition: service_healthy
      notifier:
        condition: service_healthy

  notifier:
    platform: "linux/amd64"
    build:
      context: ./src/notifier
    healthcheck:
      test: curl --fail http://127.0.0.1:5000/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1m
    restart: on-failure
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4318"
      OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
    depends_on:
      collector:
        condition: service_healthy

  frontend:
    build:
      context: ./src/frontend/
      args:
        ELASTIC_APM_SERVER_RUM_ENDPOINT: ${ELASTIC_APM_SERVER_RUM_ENDPOINT}
        ELASTIC_APM_SERVER_RUM_CREDENTIALS: ${ELASTIC_APM_SERVER_RUM_CREDENTIALS}

        KIBANA_URL: ${KIBANA_URL}
        ELASTICSEARCH_USER: ${ELASTICSEARCH_USER}
        ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
    volumes:
      - ./src/frontend/trader-app/build:/build

  proxy:
    platform: "linux/amd64"
    build:
      context: ./src/proxy/
    volumes:
      - ./src/frontend/trader-app/build:/usr/share/nginx/html
    ports:
      - '9394:80'
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4317"
      OTEL_SERVICE_NAME: "proxy"
    depends_on:
      monkey:
        condition: service_healthy
      trader:
        condition: service_healthy
      collector:
        condition: service_healthy
      frontend:
        condition: service_completed_successfully

  instruqt_frontend:
    build:
      context: ./instruqt_frontend/
    ports:
      - '9393:80'
    depends_on:
      proxy:
        condition: service_started

  postgresql:
    image: postgres:latest
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "trades"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "admin"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "trades", "-U", "admin" ]
      interval : 5s
      timeout : 5s
      retries : 5

  collector:
    image: docker.elastic.co/beats/elastic-agent:8.16.1
    restart: on-failure
    healthcheck:
      test: curl --fail http://localhost:13133/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1m
    ports:
      - "4317:4317"
    volumes:
      - ./src/collector/collector_recorder.yml:/collector.yml
      - ./logs:/logs
      - ./resources/recorded:/recorded
      - /:/hostfs
    entrypoint: "/usr/share/elastic-agent/elastic-agent"
    command: ["otel", "-c", "/collector.yml"]
    environment:
      ELASTIC_AGENT_OTEL: "true"
      ELASTIC_APM_SERVER_ENDPOINT: ${ELASTIC_APM_SERVER_ENDPOINT}
      ELASTIC_APM_SERVER_SECRET: ${ELASTIC_APM_SERVER_SECRET}
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
      ELASTICSEARCH_APIKEY: ${ELASTICSEARCH_APIKEY}
    privileged: true
    pid: "host"
    user: root
