services:

  collector_playback:
    image: docker.elastic.co/beats/elastic-agent:8.15.3
    restart: on-failure
    ports:
      - "4318:4318"
      - "4319:4319"
    volumes:
      - ./src/collector/collector_playback.yml:/collector.yml
    entrypoint: "/usr/share/elastic-agent/elastic-agent"
    command: ["otel", "-c", "/collector.yml"]
    environment:
      ELASTIC_APM_SERVER_ENDPOINT: ${ELASTIC_APM_SERVER_ENDPOINT}
      ELASTIC_APM_SERVER_SECRET: ${ELASTIC_APM_SERVER_SECRET}
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
      ELASTICSEARCH_APIKEY: ${ELASTICSEARCH_APIKEY}