#!/bin/bash

source /opt/workshops/elastic-retry.sh

echo "Wait for alert to fire"
# Wait for the Kubernetes API server to become available
retry_command_lin curl --silent --fail --output /dev/null http://localhost:9010/status/alerts
